# This workflow is triggered every time a change is pushed to any branches 
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On Code Change (PR)

# The workflow could also be triggered on PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  on-code-change:
    uses: jahia/jahia-modules-action/.github/workflows/reusable-on-code-change.yml@v2
    secrets: inherit
    with:
      module_id: augmented-search-ui
      update_signature_execute: true
      static_analysis_auditci_level: critical
      build_container_image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node
      module_branch: ${{ github.head_ref }}