# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On merge to master

# The workflow could also be triggered on PRs
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  on-merge:
    uses: jahia/jahia-modules-action/.github/workflows/reusable-on-code-change.yml@v2
    secrets: inherit
    with:
      module_id: augmented-search-ui
      update_signature_execute: true
      static_analysis_auditci_level: critical
      build_container_image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node
      module_branch: ${{ github.head_ref }}
      sbom_execute: true
      sbom_artifacts: 'build-artifacts'
      sbom_container_image: cyclonedx/cyclonedx-cli:0.24.2
      publish_execute: true
      publish_container_image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node