name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Ship the release
      run: yarn auto shipit
